-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-04-28 06:23:53 EET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

SET ECHO ON

SPOOL ad_schema_output.txt

DROP TABLE animal CASCADE CONSTRAINTS;

DROP TABLE animal_type CASCADE CONSTRAINTS;

DROP TABLE clinic CASCADE CONSTRAINTS;

DROP TABLE clinic_vet CASCADE CONSTRAINTS;

DROP TABLE drug CASCADE CONSTRAINTS;

DROP TABLE drug_rec CASCADE CONSTRAINTS;

DROP TABLE invoice CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE ownership_rec CASCADE CONSTRAINTS;

DROP TABLE prescription CASCADE CONSTRAINTS;

DROP TABLE service CASCADE CONSTRAINTS;

DROP TABLE service_rec CASCADE CONSTRAINTS;

DROP TABLE specialisation CASCADE CONSTRAINTS;

DROP TABLE vet CASCADE CONSTRAINTS;

DROP TABLE visit CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE animal (
    animal_id         NUMBER(7) NOT NULL,
    animal_gender     VARCHAR2(6) NOT NULL,
    animal_name       VARCHAR2(50) NOT NULL,
    animal_birthdate  DATE NOT NULL,
    animal_deceased   VARCHAR2(3) NOT NULL,
    animal_type_id    NUMBER(7) NOT NULL
);

ALTER TABLE animal
    ADD CONSTRAINT chk_animal_gender CHECK ( animal_gender IN ( 'F', 'M' ) );

ALTER TABLE animal
    ADD CONSTRAINT chk_animal_deceased CHECK ( animal_deceased IN ( 'N', 'Y' ) );

COMMENT ON COLUMN animal.animal_id IS
    'animal id';

COMMENT ON COLUMN animal.animal_gender IS
    'animal gender';

COMMENT ON COLUMN animal.animal_name IS
    'animal name';

COMMENT ON COLUMN animal.animal_birthdate IS
    'animal date of birth';

COMMENT ON COLUMN animal.animal_deceased IS
    'animal deceased or not';

COMMENT ON COLUMN animal.animal_type_id IS
    'animal type id';

ALTER TABLE animal ADD CONSTRAINT animal_pk PRIMARY KEY ( animal_id );

CREATE TABLE animal_type (
    animal_type_id    NUMBER(7) NOT NULL,
    animal_type_name  VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN animal_type.animal_type_id IS
    'animal type id';

COMMENT ON COLUMN animal_type.animal_type_name IS
    'animal type name';

ALTER TABLE animal_type ADD CONSTRAINT animal_type_pk PRIMARY KEY ( animal_type_id );

ALTER TABLE animal_type ADD CONSTRAINT un_animal_type_name UNIQUE ( animal_type_name );

CREATE TABLE clinic (
    clinic_id            NUMBER(7) NOT NULL,
    clinic_name          VARCHAR2(50) NOT NULL,
    clinic_address       VARCHAR2(200) NOT NULL,
    clinic_phone_number  CHAR(10)
);

COMMENT ON COLUMN clinic.clinic_id IS
    'clinic id';

COMMENT ON COLUMN clinic.clinic_name IS
    'clinic name';

COMMENT ON COLUMN clinic.clinic_address IS
    'clinic address';

COMMENT ON COLUMN clinic.clinic_phone_number IS
    'clinic phone number';

ALTER TABLE clinic ADD CONSTRAINT clinic_pk PRIMARY KEY ( clinic_id );

CREATE TABLE clinic_vet (
    clinic_id  NUMBER(7) NOT NULL,
    vet_id     NUMBER(7) NOT NULL
);

ALTER TABLE clinic_vet ADD CONSTRAINT clinic_vet_pk PRIMARY KEY ( clinic_id,
                                                                  vet_id );

CREATE TABLE drug (
    drug_id                  NUMBER(7) NOT NULL,
    drug_name                VARCHAR2(50) NOT NULL,
    drug_usage_instructions  VARCHAR2(250) NOT NULL,
    drug_cost                NUMBER(7, 2) NOT NULL
);

COMMENT ON COLUMN drug.drug_id IS
    'drug id';

COMMENT ON COLUMN drug.drug_name IS
    'drug name';

COMMENT ON COLUMN drug.drug_usage_instructions IS
    'drug usage instructions';

COMMENT ON COLUMN drug.drug_cost IS
    'drug cost';

ALTER TABLE drug ADD CONSTRAINT drug_pk PRIMARY KEY ( drug_id );

CREATE TABLE drug_rec (
    drug_req_qty_supplied  NUMBER(7) NOT NULL,
    drug_id                NUMBER(7) NOT NULL,
    invoice_id             NUMBER(7) NOT NULL
);

COMMENT ON COLUMN drug_rec.drug_req_qty_supplied IS
    'drug quantity supplied';

COMMENT ON COLUMN drug_rec.drug_id IS
    'drug id';

COMMENT ON COLUMN drug_rec.invoice_id IS
    'surrogate key';

ALTER TABLE drug_rec ADD CONSTRAINT drug_rec_pkv1 PRIMARY KEY ( drug_id,
                                                                invoice_id );

ALTER TABLE drug_rec ADD CONSTRAINT drug_rec_pk UNIQUE ( drug_id );

CREATE TABLE invoice (
    invoice_date        DATE NOT NULL,
    invoice_time        VARCHAR2(15) NOT NULL,
    invoice_total_due   NUMBER(7, 2) NOT NULL,
    invoice_pay_method  VARCHAR2(20) NOT NULL,
    animal_id           NUMBER(7) NOT NULL,
    vet_id              NUMBER(7) NOT NULL,
    invoice_id          NUMBER(7) NOT NULL
);

COMMENT ON COLUMN invoice.invoice_date IS
    'invoice date';

COMMENT ON COLUMN invoice.invoice_time IS
    'invoice time';

COMMENT ON COLUMN invoice.invoice_total_due IS
    'invoice total due';

COMMENT ON COLUMN invoice.invoice_pay_method IS
    'invoice payment method';

COMMENT ON COLUMN invoice.animal_id IS
    'animal id';

COMMENT ON COLUMN invoice.vet_id IS
    'vet id';

COMMENT ON COLUMN invoice.invoice_id IS
    'surrogate key';

ALTER TABLE invoice ADD CONSTRAINT invoice_pk PRIMARY KEY ( invoice_id );

ALTER TABLE invoice ADD CONSTRAINT invoice_nk UNIQUE ( vet_id,
                                                       animal_id );

ALTER TABLE invoice ADD CONSTRAINT inoice_nk UNIQUE ( vet_id,
                                                      animal_id );

CREATE TABLE owner (
    owner_id            NUMBER(7) NOT NULL,
    owner_given_name    VARCHAR2(50) NOT NULL,
    owner_family_name   VARCHAR2(50) NOT NULL,
    owner_street        VARCHAR2(50) NOT NULL,
    owner_town          VARCHAR2(50) NOT NULL,
    owner_postcode      CHAR(5) NOT NULL,
    owner_pref_vet_id   NUMBER(7),
    owner_phone_number  CHAR(10)
);

COMMENT ON COLUMN owner.owner_id IS
    'owner id number';

COMMENT ON COLUMN owner.owner_given_name IS
    'owner given name';

COMMENT ON COLUMN owner.owner_family_name IS
    'owner family name';

COMMENT ON COLUMN owner.owner_street IS
    'owner street';

COMMENT ON COLUMN owner.owner_town IS
    'owner town';

COMMENT ON COLUMN owner.owner_postcode IS
    'owner postal code';

COMMENT ON COLUMN owner.owner_pref_vet_id IS
    'the owner prefered vet  id';

COMMENT ON COLUMN owner.owner_phone_number IS
    'owner phone number';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE ownership_rec (
    owner_id          NUMBER(7) NOT NULL,
    animal_id         NUMBER(7) NOT NULL,
    ownership_rec_id  NUMBER(7) NOT NULL
);

COMMENT ON COLUMN ownership_rec.owner_id IS
    'owner id number';

COMMENT ON COLUMN ownership_rec.animal_id IS
    'animal id';

COMMENT ON COLUMN ownership_rec.ownership_rec_id IS
    'surrogate key';

CREATE UNIQUE INDEX ownership_rec__idx ON
    ownership_rec (
        animal_id
    ASC );

ALTER TABLE ownership_rec ADD CONSTRAINT ownership_rec_pk PRIMARY KEY ( ownership_rec_id );

ALTER TABLE ownership_rec ADD CONSTRAINT ownership_rec_nk UNIQUE ( animal_id,
                                                                   owner_id );

CREATE TABLE prescription (
    prescription_drug_dose  VARCHAR2(100) NOT NULL,
    prescription_drug_freq  VARCHAR2(100) NOT NULL,
    drug_id                 NUMBER(7) NOT NULL,
    visit_date              DATE NOT NULL,
    visit_time              VARCHAR2(15) NOT NULL,
    animal_id               NUMBER(7) NOT NULL,
    prescription_id         NUMBER(7) NOT NULL
);

COMMENT ON COLUMN prescription.prescription_drug_dose IS
    'prescription drug dose';

COMMENT ON COLUMN prescription.prescription_drug_freq IS
    'prescription drug frequency of adminstration';

COMMENT ON COLUMN prescription.drug_id IS
    'drug id';

COMMENT ON COLUMN prescription.visit_date IS
    'visit date';

COMMENT ON COLUMN prescription.visit_time IS
    'visit time';

COMMENT ON COLUMN prescription.animal_id IS
    'animal id';

COMMENT ON COLUMN prescription.prescription_id IS
    'surrogate key';

ALTER TABLE prescription ADD CONSTRAINT prescription_pk PRIMARY KEY ( prescription_id );

ALTER TABLE prescription
    ADD CONSTRAINT prescription_nk UNIQUE ( drug_id,
                                            visit_date,
                                            visit_time,
                                            animal_id );

CREATE TABLE service (
    service_code  NUMBER(7) NOT NULL,
    service_desc  VARCHAR2(50) NOT NULL,
    service_cost  NUMBER(7, 2) NOT NULL
);

COMMENT ON COLUMN service.service_code IS
    'service code';

COMMENT ON COLUMN service.service_desc IS
    'service description';

COMMENT ON COLUMN service.service_cost IS
    'service cost';

ALTER TABLE service ADD CONSTRAINT service_pk PRIMARY KEY ( service_code );

CREATE TABLE service_rec (
    service_code    NUMBER(7) NOT NULL,
    service_req_id  NUMBER(7) NOT NULL,
    invoice_id      NUMBER(7) NOT NULL
);

COMMENT ON COLUMN service_rec.service_code IS
    'service code';

COMMENT ON COLUMN service_rec.service_req_id IS
    'surrogate key';

COMMENT ON COLUMN service_rec.invoice_id IS
    'surrogate key';

ALTER TABLE service_rec ADD CONSTRAINT service_rec_pk PRIMARY KEY ( service_req_id );

ALTER TABLE service_rec ADD CONSTRAINT service_req_nk UNIQUE ( service_code,
                                                               invoice_id );

ALTER TABLE service_rec ADD CONSTRAINT service_rec_nk UNIQUE ( service_code,
                                                               invoice_id );

CREATE TABLE specialisation (
    specialisation_id    NUMBER(7) NOT NULL,
    specialisation_name  VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN specialisation.specialisation_id IS
    'specialisation id';

COMMENT ON COLUMN specialisation.specialisation_name IS
    'specialisation name';

ALTER TABLE specialisation ADD CONSTRAINT specialisation_pk PRIMARY KEY ( specialisation_id );

ALTER TABLE specialisation ADD CONSTRAINT un_specialisation_name UNIQUE ( specialisation_name );

CREATE TABLE vet (
    vet_id                 NUMBER(7) NOT NULL,
    vet_given_name         VARCHAR2(50) NOT NULL,
    vet_family_name        VARCHAR2(50) NOT NULL,
    vet_phone_number       CHAR(10),
    vet_first_employ_date  DATE NOT NULL,
    specialisation_id      NUMBER(7)
);

COMMENT ON COLUMN vet.vet_id IS
    'vet id';

COMMENT ON COLUMN vet.vet_given_name IS
    'vet given name';

COMMENT ON COLUMN vet.vet_family_name IS
    'vet family name';

COMMENT ON COLUMN vet.vet_phone_number IS
    'vet phone number';

COMMENT ON COLUMN vet.vet_first_employ_date IS
    'vet first employment date';

COMMENT ON COLUMN vet.specialisation_id IS
    'specialisation id';

ALTER TABLE vet ADD CONSTRAINT vet_pk PRIMARY KEY ( vet_id );

CREATE TABLE visit (
    visit_date           DATE NOT NULL,
    visit_time           VARCHAR2(15) NOT NULL,
    visit_length         VARCHAR2(15) NOT NULL,
    visit_notes          VARCHAR2(250),
    clinic_id            NUMBER(7) NOT NULL,
    vet_id               NUMBER(7) NOT NULL,
    visit_prev_visit_id  NUMBER(7),
    animal_id            NUMBER(7) NOT NULL
);

COMMENT ON COLUMN visit.visit_date IS
    'visit date';

COMMENT ON COLUMN visit.visit_time IS
    'visit time';

COMMENT ON COLUMN visit.visit_length IS
    'visit length';

COMMENT ON COLUMN visit.visit_notes IS
    'visit notes';

COMMENT ON COLUMN visit.clinic_id IS
    'clinic id';

COMMENT ON COLUMN visit.vet_id IS
    'vet id';

COMMENT ON COLUMN visit.visit_prev_visit_id IS
    'previous visit id, if any';

COMMENT ON COLUMN visit.animal_id IS
    'animal id';

ALTER TABLE visit
    ADD CONSTRAINT visit_pk PRIMARY KEY ( visit_date,
                                          visit_time,
                                          animal_id );

ALTER TABLE invoice
    ADD CONSTRAINT animal_invoice FOREIGN KEY ( animal_id )
        REFERENCES animal ( animal_id );

ALTER TABLE ownership_rec
    ADD CONSTRAINT animal_ownershiprec FOREIGN KEY ( animal_id )
        REFERENCES animal ( animal_id );

ALTER TABLE visit
    ADD CONSTRAINT animal_visit FOREIGN KEY ( animal_id )
        REFERENCES animal ( animal_id );

ALTER TABLE animal
    ADD CONSTRAINT animaltype_animal FOREIGN KEY ( animal_type_id )
        REFERENCES animal_type ( animal_type_id );

ALTER TABLE clinic_vet
    ADD CONSTRAINT clinic_vet_clinic_fk FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE clinic_vet
    ADD CONSTRAINT clinic_vet_vet_fk FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE visit
    ADD CONSTRAINT clinic_visit FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE drug_rec
    ADD CONSTRAINT drug_drugrec FOREIGN KEY ( drug_id )
        REFERENCES drug ( drug_id );

ALTER TABLE prescription
    ADD CONSTRAINT drug_prescription FOREIGN KEY ( drug_id )
        REFERENCES drug ( drug_id );

ALTER TABLE drug_rec
    ADD CONSTRAINT invoice_drugrec FOREIGN KEY ( invoice_id )
        REFERENCES invoice ( invoice_id );

ALTER TABLE service_rec
    ADD CONSTRAINT invoice_servicerec FOREIGN KEY ( invoice_id )
        REFERENCES invoice ( invoice_id );

ALTER TABLE ownership_rec
    ADD CONSTRAINT owner_ownershiprec FOREIGN KEY ( owner_id )
        REFERENCES owner ( owner_id );

ALTER TABLE service_rec
    ADD CONSTRAINT service_servicerec FOREIGN KEY ( service_code )
        REFERENCES service ( service_code );

ALTER TABLE vet
    ADD CONSTRAINT specialisation_vet FOREIGN KEY ( specialisation_id )
        REFERENCES specialisation ( specialisation_id );

ALTER TABLE invoice
    ADD CONSTRAINT vet_invoice FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE visit
    ADD CONSTRAINT vet_visit FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE prescription
    ADD CONSTRAINT visit_prescription FOREIGN KEY ( visit_date,
                                                    visit_time,
                                                    animal_id )
        REFERENCES visit ( visit_date,
                           visit_time,
                           animal_id );

spool off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             1
-- ALTER TABLE                             43
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
